[package]
name = "ics-filter"
version = "1.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.42"
diesel = { version = "2.3.3", features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
icalendar = { version = "0.17.5", features = ["parser"] }
