[[calendars]]
url = ""
blacklist = []

[[calendars]]
url = ""
whitelist = []

[git.signature]
username = ""
email = ""

[git.remote]
domain = ""
repository = ""
username = ""
token = ""

[notifications.email]
smtp_server = ""
username = ""
password = ""
recipients = []

[notifications.gotify]
server = ""
token = ""
